keys:
  - &eritho23 age1za4x2kz9kuus40c5tfznckcy9vfrqzt6m0kclpr5q52lcx6fxywq2t9str
  - &hg age14ndqlhwyxarn9c4a5h69derse6jc5lwladfntvczmtq2n5s9zfwsnhm8cy
creation_rules:
  - path_regex: secrets/secrets.env$
    key_groups:
      - age:
          - *eritho23
          - *hg
